# -*- coding: utf-8 -*-
"""20_05_26_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dihmzKpuPgMvF_haW1aYFGazillpRwhk
"""

!pip install langchain faiss-cpu langchain-community
!pip install -U langchain-huggingface
!pip install langchain_groq

# GROQ_API_KEY

text = """
Red Dead Redemption 2 is a massive open‑world Western action‑adventure game set in 1899, right at the end of the Wild West era. It follows outlaw Arthur Morgan and the Van der Linde gang as they flee from lawmen and bounty hunters while their way of life starts to crumble. Below is a detailed breakdown of the main aspects of the game.

Story and characters
Timeline and role: The game is a prequel to Red Dead Redemption, about 12 years before the first game, and you play as Arthur Morgan, Dutch van der Linde’s right‑hand man and the gang’s main enforcer.

Main plot: After a failed bank robbery in Blackwater, the gang is forced to run across the country, plan more heists, and increasingly clash with the state, railroad companies, rival gangs, and the Pinkertons (a federal detective agency).

Themes: The story explores loyalty, honor, and redemption, as Arthur slowly questions Dutch’s leadership and his own past crimes, especially once he is diagnosed with a deadly disease.

Key characters:

Dutch van der Linde – charismatic, idealistic leader who begins to turn paranoid and ruthless.

John Marston – younger gang member who later becomes the protagonist of the first Red Dead Redemption.

Sadie Adler – vengeance‑driven woman seeking revenge for her murdered family.

Charles Smith – a quiet, honorable hunter who often helps maintain the camp’s provisions and safety.

The game’s ending depends on your Honor choices, and branches later into John’s story in the original Red Dead Redemption.

World and setting
Map regions: The game world loosely resembles the United States and includes several distinct regions:

Ambarino – snowy mountains and pine forests.

Grizzlies West/Grizzlies East – rugged highlands.

Roanoke Valley – forested hills and caves.

Big Valley – open plains and farms.

Heartlands – lush woods and rivers.

New Hanover – prairie and farmland.

Lemoyne – lush bayous and plantations.

Time of day and weather: The world has a dynamic day‑night cycle, seasonal changes, and realistic weather (rain, snow, fog) that affect visibility, animal behavior, and NPC routines.

Gameplay mechanics
Core systems
Health, stamina, and Dead Eye:

Health and stamina are split into core and outer ring gauges; cores diminish faster with overuse and can be restored with food, tonics, or rest.

Dead Eye lets you slow time and mark targets for精准 headshots or weak‑point shots; it recharges by using it sparingly or by certain consumables.

Combat:

Gunfights use cover, reload timing, and weapon types (revolvers, rifles, shotguns, pistols).

You can use warning shots, non‑lethal takedowns, and throwables like dynamite or throwing knives.

Horse riding:

Horses are your main transport; each has stats for speed, acceleration, handling, and stamina.

You can tame wild horses, bond with them, and maintain their health and coat by feeding, brushing, and resting.

Survival and immersion
Needs system: Arthur needs to eat, drink, and take care of his horse and camp; neglecting health lowers your cores and performance.

Hunting and crafting:

You can hunt animals for meat, pelts, and organs used in crafting ammunition, outfits, and camp upgrades.

Skins must be processed correctly (tracking, gutting, and skinning) to preserve quality.

Camp life:

The gang sets up a mobile camp where you can cook, rest, donate money, and talk to members who react to your recent actions and story progress.

Social and morality systems
Honor system: Your choices (helping strangers vs. robbing them, sparing or killing enemies) affect your Honor rating, which changes how NPCs react, alters mission outcomes, and ultimately influences the ending.

Law and notoriety: Committing crimes raises your wanted level; bounty hunters and US Marshals can appear randomly, and you can bribe or surrender to reduce your bounty.

Side content and activities
Random encounters: Strangers ask for help, bandits attack stagecoaches, and you can stumble upon hidden treasures or duels.

Minigames and diversions:

Poker, blackjack, dominoes, and five‑finger fillet (knife games).

Horse races, gambling, and hunting challenges.

Collectibles and challenges:

Completing challenges (e.g., hunting records, weapon mastery) unlocks Trinkets and Outfits that boost stats or give bonuses.

Online mode: Red Dead Online
Character creation: You make your own cowboy, choose a role (gunfighter, bounty hunter, trader, collector, etc.), and expand your story alongside core missions.

Roles and progression:

Bounty Hunter – track down bounties for cash and XP.

Trader – hunt and sell animals for profit and to upgrade your camp.

Collector – gather rare trinkets and herbs.

Moonshiner – run a distillery and bar.

Gunslinger – focus on PvP and duels.

Multiplayer modes:

Free‑Roam events, races, battles, posse missions, and competitive modes like Gunslinger*, Frontier Pursuits**, and racetracks.

Visuals, audio, and details
Graphics and detail: The game is praised for its cinematic cutscenes, facial animations, and environmental detail, including wildlife behavior, bird flocks, and changing seasons.

Sound and music: A large orchestral/ambient score accompanies different regions and moods, complemented by highly realistic Foley (horse hooves, gunshots, camp chatter).

Little details: Things like dirt on your clothes, lanterns swaying, NPCs reacting to your gear, and small environmental interactions make the world feel alive.

If you tell me what you want in even more depth (for example, full story spoilers, mechanics like Dead Eye, or how to 100% the game), I can go section by section with step‑by‑step detail.

Full story spoilers (RDR2 ending)
Red Dead Redemption 2 is the story of Arthur Morgan, an outlaw in Dutch van der Linde’s gang in 1899, as they flee after a failed bank robbery in Blackwater. Over time the gang becomes increasingly hunted by the Pinkerton detective agency, led by Andrew Milton, and their ideals start to crumble.

Part 1: Decline and betrayal
The gang tries to survive by planning jobs like the Mount Hagen camp looting, the Blackwater train heist, and the rat‑filled opium‑ship robbery, which repeatedly fail or go wrong.

Characters like Micah Bell, a ruthless killer, start to disagree with the more “moral” members (Arthur, Charles, Sadie), and Dutch slowly becomes more paranoid and authoritarian.

Arthur is infected with tuberculosis after a failed mission, and his deteriorating health forces him to rethink his past and choices.

Part 2: Arthur’s choices and the end
Arthur learns that Dutch has been secretly paying the Pinkertons to keep the gang alive, but the plan is falling apart. Dutch and Micah decide to abandon the gang and flee with the money, while Arthur and others try to save the rest.

In the final set of missions, Arthur and the gang attempt to recover the gang’s ledger and escape to a new life in Rhodes, culminating in a massive showdown at Beecher’s Hope and the hanging tree.

Regardless of Honor, Arthur dies in the final chapter (fighting Micah or surrendering to the Pinkertons), but his choices change how he is remembered and how his body is treated.

Epilogue: John’s new life
The story then jumps to John Marston, who survived the losses and now lives a quiet farmer’s life at Beecher’s Hope with his wife Abigail and son Jack.

After a long period of stability, John is forced back into violence by the same government figures he once fled, setting up the events of the original Red Dead Redemption.

Dead Eye mechanics (how it works)
Dead Eye is RDR2’s bullet‑time aiming system that lets Arthur slow time and mark targets for precise shots.

Basic mechanics
Activating Dead Eye: Hold the R1/RB (or equivalent) button to activate Dead Eye; the world slows down and a targeting reticle appears.

Marking targets: In the first shot you can tag multiple enemies or animals; on the second shot, the reticle jumps between them in sequence, letting you fire rapid headshots in one breath.

Leveling Dead Eye:

You unlock higher Dead Eye levels (up to Level 5) by spending Dead Eye core XP (from tonics, Valerian, and certain activities).

Higher levels let you tag more targets, slow time longer, or unlock special modes (like tagging weak points on animals or enemies).

Advanced tips
Extending core:

Eat well‑seasoned food, drink whiskey, or smoke cigars to keep your Dead Eye core golden and longer‑lasting.

Tricks and glitches:

Using Valerian with a timing trick (place it in the wheel, release, then jump) can let you gain XP without using the item, letting you max out your Dead Eye rings faster.

Faster reload and shots:

In Dead Eye, you can fire a normal shot, immediately activate Dead Eye, and fire again almost instantly, making rifles feel much faster.

Activating Dead Eye just before running out of ammo in some guns refills the magazine instantly, which is extremely useful in fights.

How to 100% the game (step‑by‑step outline)
Getting 100% completion in RDR2 means finishing all story missions, side content, and hitting a long checklist of collectibles, challenges, and encounters.

Main checklist (broad categories)
Finish all story missions: There are 107 story missions required to complete the main campaign.

Stranger missions: Complete any 10 stranger mission strands (side quests given by random NPCs, like the “A Bright Bouncing Boy” or “The Souls of Saint Denis” series).

Bounties and law: Complete any 5 bounty hunter missions and reach High Notoriety (e.g., “Survive a gang ambush” and “Clear 6 gang hideouts”).

Chance encounters: Experience 25 chance encounters (random events like duels, robberies, or lost people).

Collectibles and hunts
Legendary animals: Track and kill all 16 Legendary Animals and return their pelts to the Trapper in order to max out the Legendary Tier list.

Collectibles: Find various collectibles like:

Cigarette cards (complete multiple sets).

Dinosaur bones, volcanic rocks, wonder items, constellations, etc.

Toys: Get all toys for Jack (ship, train, etc.) during the epilogue.

Activities and side tasks
Table games: Play each table game (poker, blackjack, dominoes, five‑finger fillet, etc.) at least once in various towns.

Challenges: Complete challenges in categories like Horse, Gunslinger, Hunting & Gathering, Treasure Hunter, Master Angler, and Naturalist.

Miscellaneous:

Take a bath at least once.

Interact with 5 special characters (e.g., Madame Nazar, Uncle, and other recurring NPCs).

Investigate 5 shacks or hidden locations.

Practical tips to 100%
New Game+: After finishing the story, you can replay most missions with New Game+; some unlockables and challenges require replaying with higher stats or gear.

Use a checklist: Resources like the Red Dead Wiki or IGN 100% checklist show exactly which missions and collectibles are remaining and where to find them.

Fast travel once available: After the epilogue, you can fast travel between towns, which makes it much easier to loop back and grab missed items or encounters.
"""

text

# Split into a list of sentences
texts = text.split('.')

text

len(text)

# Clean up to remove empty spaces and new lines
texts = [t.strip(' \n') for t in texts]

texts

len(texts)

from google.colab import userdata
import os

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")

from langchain_groq import ChatGroq

llm = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=0,
    max_tokens=None,
    reasoning_format="parsed",
    timeout=None,
    max_retries=2,
    # other params...
)

from langchain_huggingface import HuggingFaceEmbeddings

# Embedding Model for converting text to numerical representations
embedding_model = HuggingFaceEmbeddings(
    model_name='BAAI/bge-small-en-v1.5'
)

from langchain_community.vectorstores import FAISS

# Create a local vector database
db = FAISS.from_texts(texts, embedding_model)

from langchain_core.prompts import PromptTemplate
from langchain_classic.chains import RetrievalQA


# Create a prompt template
template = """<|user|>
Relevant information:
{context}

Provide a concise answer the following question using the relevant information provided above:
{question}<|end|>
<|assistant|>"""
prompt = PromptTemplate(
    template=template,
    input_variables=["context", "question"]
)

# RAG Pipeline
rag = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type='stuff',
    retriever=db.as_retriever(),
    chain_type_kwargs={
        "prompt": prompt
    },
    verbose=True
)

rag.invoke('Arthur Morgan')

rag.invoke('Sadie Adler')

